[versions]

# Sdk
sdk-min = "24"
sdk-target = "36"
sdk-compile = "36"

# Plugin
plugin-gradle = '8.13.2'
plugin-kotlin = '2.3.0'

# BOM
bom-compose = '2025.12.01'

# AndroidX
androidx-activity-compose = '1.12.2'
androidx-lifecycle = '2.10.0'

# Third Party
third-party-reachard = '2.2.0'

# Unit Test
unit-test-junit = '4.13.2'

[plugins]

android-application = { id = "com.android.application", version.ref = "plugin-gradle" }
android-library = { id = "com.android.library", version.ref = "plugin-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "plugin-kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "plugin-kotlin" }

[libraries]

# BOM Compose
bom-compose = { group = "androidx.compose", name = "compose-bom", version.ref = "bom-compose" }
bom-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
bom-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
bom-compose-ui = { group = "androidx.compose.ui", name = "ui" }
bom-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }

# AndroidX
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }

# Third Party
third-party-reachard-di = { group = "com.github.kuyucuburak.Reachard", name = "reachard-di", version.ref = "third-party-reachard" }
third-party-reachard-namifier = { group = "com.github.kuyucuburak.Reachard", name = "reachard-namifier", version.ref = "third-party-reachard" }

# Unit Test
unit-test-junit = { group = "junit", name = "junit", version.ref = "unit-test-junit" }
