name: Eligibility Bot

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build, Analyze and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "11.x"
          distribution: "zulu"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Clean
        uses: ./gradlew clean

      - name: Build
        uses: ./gradlew build
